config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "excel#newSheet"
  post "excel", to: "excel#uploadSheet"

  #for Json API
  namespace :api do
    namespace :v1 do
      resources :customers, only: [:index, :show]
    end
  end

  #for pagination with editing ability
  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :mobile, :name, :address, presence: true
  validates :mobile, uniqueness: true
end

app/models/customer_data_sheet.rb
class CustomerDataSheet < ApplicationRecord
  has_one_attached :sheet
  validates :sheet, presence: true
end

app/controllers/api/v1/customers_controller.rb
class Api::V1::CustomersController < ApplicationController

  def index
    @customers = Customer.order(name: :ASC)
    render json: @customers
  end

  def show
    @customer = Customer.find(params[:id])
    render json: @customer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include Pagy::Backend

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def record_not_found
    render 'error' # Assuming you have a template named 'record_not_found'
  end
end

app/controllers/customers_controller.rb
require 'pagy/extras/bootstrap'

class CustomersController < ApplicationController
  before_action :setCustomer, only: [:destroy, :edit, :show]

  def index
    @page_size = params[:page_size] || 5
    @pagy, @customers = pagy(Customer.order(name: :ASC), items: params[:page_size] || 5)
  end

  def show
  end

  def destroy
    @customer.destroy
    redirect_to customers_path
  end

  def edit
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(params_customer)
      redirect_to customers_path, notice: "customer updated"
    else
      render :edit
    end
  end
  

  private
  def setCustomer
    @customer = Customer.find(params[:id])
  end

  def params_customer
    params.require(:customer).permit(:mobile, :name, :address)
  end
end

app/controllers/excel_controller.rb
class ExcelController < ApplicationController
  def newSheet
    @sheet = CustomerDataSheet.new
  end

  def uploadSheet
    @sheet = CustomerDataSheet.new(sheet_params)

    if @sheet.save
      CustomerDataEntryJob.perform_later @sheet
      redirect_to root_path , notice: "Successfully uploaded"
    else
      render :newSheet
    end 
  end


  private
  def sheet_params
    params.require(:customer_data_sheet).permit(:sheet)
  end
end

app/helpers/api/v1/customers_helper.rb
module Api::V1::CustomersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/customers/_customer_card.html.erb
<div class="card myCard">
    <div class="card-body">
      <h5 class="card-title"><%= customer.name%></h5>
      <p class="card-text"><%=t("mobile_label")%><%= customer.mobile%> </p>
      <p class="card-text"> <%=t("address_label")%><%= customer.address%></p>

      <div class="dropdown">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="blue" class="bi bi-sliders dropdown-toggle" viewBox="0 0 16 16" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
        </svg>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><%= button_to "Edit", edit_customer_path(customer), method: :get, class: "dropdown-item"%></li>
          <li><%= button_to "Delete", customer_path(customer), method: :delete, data: {confirm: "Are you sure"}, class: "dropdown-item"%></li>
        </ul>
      </div>
    </div>
  </div>

app/views/customers/_page_size_dropdown_menu.html.erb
<div class="container">
  <div class="row">
    <div class="col mt-4">
      <%= form_tag customers_path, method: :get do %>
        <%=label_tag :page_size%>
        <%= select_tag(:page_size,
          options_for_select([
            [t("nums")[1], 1],
            [t("nums")[2], 2],
            [t("nums")[3], 3],
            [t("nums")[4], 4],
            [t("nums")[5], 5],
            [t("nums")[6], 6],
            [t("nums")[7], 7],
            [t("nums")[8], 8],
            [t("nums")[9], 9],
            [t("nums")[10], 10],
          ]),
          {
            prompt: current_size,
            onchange: 'this.form.submit()',
            class: "btn btn-secondary btn-sm"
          }
        )%>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/edit.html.erb
<h1><%=t("edit_custumer_header")%></h1>

<%= form_with model: @customer, url: customer_path do |form| %>

    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |message| %>
                <div> <%= message %> </div>
            <%end%>
        </div>
    <%end%>

    <div class="mb-3">
        <%= form.label :mobile %>
        <%= form.text_field :mobile, class: "form-control", placeholder: "+20 1478596266"%>
    </div>

    <div class="mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control", placeholder: "Nour Mahmoud"%>
    </div>

    <div class="mb-3">
        <%= form.label :address %>
        <%= form.text_field :address, class: "form-control", placeholder: "7 st elHuda"%>
    </div>

    <div class="mb-3">
        <%= form.submit "Update Customer" , class: "btn btn-primary"%>
    </div>

<%end%>

app/views/customers/error.html.erb
<h1><%=t("not_found_msg")%></h1>

app/views/customers/index.html.erb
<h1> <%=t("customers_header")%> </h1>

<% @customers.each do |customer| %>
  <%=render "customer_card", customer: customer%>
<% end %>

<%=render "page_size_dropdown_menu", current_size: @page_size%>

<div class = "mt-4">
  <%= pagy_bootstrap_nav(@pagy).html_safe %>
</div>

app/views/customers/show.html.erb
<%= @customer.name %>

app/views/excel/newSheet.html.erb
<h1> Upload Excel Sheet </h1>

<%= form_with model: @sheet, url: excel_path do |form| %>

  <%= render "shared/form_errors", form: form %>
  
  <div class="mb-9">
    <%= form.file_field :sheet, accept: ".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" %>
  </div>


  <div class="mb-3">
    <%= form.submit "Upload" , class: "btn btn-primary"%>
  </div>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AddCustomersData</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial:"shared/navbar" %>

    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
  <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |message| %>
      <div> <%= message %> </div>
    <%end%>
  </div>
<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "Upload File", root_path, class:"nav-link" %>
        
          </li>
          <li class="nav-item">
          <%= link_to "Customers", customers_path, class:"nav-link" %>
          </li> 
        
        </li>
        <li class="nav-item">
        <%= link_to "Customer API", api_v1_customers_path, class:"nav-link" %>
        </li>
      </ul>

    </div>
  </div>
</nav>